# .coderabbit.yaml
reviews:
  paths:
    exclude:
      - "dist/**"
      - "_generated/**"
      - "./apps/web/components/animated-icons/*"
      - "node_modules/**"
      - "**/*.min.js"
      - "docs/**"
